### ISSUE TITLE
Permissions - Deny permissions on Android Marshmellow will show empty main screen

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#1]
![domoticz_empty](https://cloud.githubusercontent.com/assets/3482284/11256299/70998050-8e4b-11e5-92e3-f8dbcc0ccf1c.png)

**Comment by galadril** [comment]
Should be fixed in v0.1.133

**Comment by RoadXY** [comment]
Solved but not very friendly solution in my humble opinion.
But this is almost the same as #6 now so maybe continue there.
