### ISSUE TITLE
i18n - key duplication

### ISSUE THREAD

**Issue by fchauveau** [galadril/DomoticzForAndroid#105]
Hello, 

during my translations to french, i've seen many keys that was targeting same words like for `goefencing`, `switches`...

Are you okay if I try a refactor for removing most of theses duplicate keys ?
I think it would simplify work for next people that will translate in their own language.

Thx

**Comment by RoadXY** [comment]
Yeah, I know but sometimes the translation is not the same in every language.
I've learned that at the time I was translating from English to Dutch for CyanogenMod ROM.

**Comment by fchauveau** [comment]
Okay, no problem
