### ISSUE TITLE
Smoke sensor - wrong type?

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#107]
Smoke sensor is seen as a switch.
But it should not be switchable.
Also there shouldn't be a log button because that will produce an error when pressed.

**Comment by galadril** [comment]
"Smoke sensor is seen as a switch."
Just like in Domoticz, but your smoke sensor doesn't handle the on-command (we discussed this via chat)

The log button needed a fix, can you check in v0.1.156 if it;'s now working?

**Comment by RoadXY** [comment]
Will check!

**Comment by RoadXY** [comment]
Works!
