### ISSUE TITLE
GPS - GPS not stopped when losing focus while in the Geofence screen

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#11]
It seems like GPS is not stopped when leaving the Geofence setting screen open while switching to another app or home screen

**Comment by galadril** [comment]
Geofence adds locations to the Geofence API of Google, which adds a watch on GPS in the background. I don't do anything with GPS directly

**Comment by RoadXY** [comment]
If I close Domoticz by going to the recent apps and swiping away Domoticz GPS stops

**Comment by galadril** [comment]
You fixed this with your last commit right?

**Comment by RoadXY** [comment]
Should be, yes ;-)

**Comment by RoadXY** [comment]
Is the Geofence feature still working as intended?
I did some simple tests and all seemed fine.

**Comment by galadril** [comment]
It still triggered this morning when i went to work :)

**Comment by RoadXY** [comment]
Great! Haven't changed code in the Geofence service so it should still work as intended.
