### ISSUE TITLE
Blinds, status not being refreshed

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#112]
Normal blinds
RFY

Video:
https://youtu.be/VL9wGK5FVS0

**Comment by galadril** [comment]
Do you see the Data (open/closed) being refreshed when you have more information (extra data turned on) shown on the Dashboard page?

Is the last seen date updated within Domoticz?

Normally we just set the new value ourselfs on the object and don't refresh via the database after an action.. so Data, on/off, that get's updated.. not the last seen (not so important right??)

**Comment by RoadXY** [comment]
Nope, I'll have a look. Kids are sleeping ;-)

**Comment by galadril** [comment]
I've fixed this in the next version.
