### ISSUE TITLE
Widget status not updated

### ISSUE THREAD

**Issue by arjen8** [galadril/DomoticzForAndroid#116]
Hi,

When I toggle a switch on in the app or in the domoticz web interface, the widget status of this switch isn't updated.

Is this possible to achieve?

**Comment by galadril** [comment]
The widgets are updated every 30 minutes (that the minimal time specified by Google).
i'll change the app so that the widgets get updated when you toggle a switch in the app!

But I can't change that widgets are updated when you do something via the web interface...

**Comment by galadril** [comment]
"i'll change the app so that the widgets get updated when you toggle a switch in the app!"
I've fixed this in the next version
