### ISSUE TITLE
Resume app - Leaving from settings and going back not correct

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#12]
While leaving the settings screen open going to another app or home screen, opening the app through the icon will not resume to the settings page you left but rather to the main screen.
Opening settings from the main screen will however continue where you left off.

**Comment by galadril** [comment]
Please check in verison v0.1.133
(already uploaded this new version to play store earlier..)

**Comment by RoadXY** [comment]
Great work!

**Comment by galadril** [comment]
Dus werkt? dan kan deze eventueel ook op slot :)

**Comment by RoadXY** [comment]
Haven't received the update (yet), sorry for the confusion.

**Comment by RoadXY** [comment]
Update!

Is solved for settings but not for Geofence Activity, sorry.
Ok, after 5 tries it started working. Will keep testing it more.
