### ISSUE TITLE
Widget updates

### ISSUE THREAD

**Issue by jjnj023** [galadril/DomoticzForAndroid#120]
Widgets do not update automatically/periodically only after manually opening the app the information will be refreshed.

No temp. / power consumption / switch status is updated. 

I understand there is an impact on battery life but this should be very limited. You can even make an option for the end-user to select how often to update: 15 seconds, 30, 60 etc...

**Comment by galadril** [comment]
"Android system forces the minimum update time to be 30 minutes."

**Comment by jjnj023** [comment]
I wasn't aware sorry. If this cannot be changed we can close this item.

**Comment by RoadXY** [comment]
This is to protect the user.
Otherwise your phone would run out of battery and the user would blame Domoticz :-p
