### ISSUE TITLE
Wear devices

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#127]
from domoticz forum:

Bug: the order of the switches on my wear change, they open random? And after a second they are ordered alphabetically.

Not all kind of devices are available on wear.

Wear: Domoticz first time long loading.

**Comment by galadril** [comment]
I;ve fixed the sorting on wear on alphanummeric in the next version!

**Comment by RoadXY** [comment]
Do you experience any long loading @galadril ?
@Joost?

**Comment by galadril** [comment]
No i don't experience long loading...

**Comment by galadril** [comment]
Maybe it's already quicker, because I changed the switch commands to device commands...

**Comment by jjnj023** [comment]
It takes about <2 seconds for the watch to load the app. After pressing a switch the devices state is toggled almost instantly. (paid app)

**Comment by jjnj023** [comment]
But it would be nice to have scenes in the wear app. I almost only use scenes on wear right now (tasker)

**Comment by RoadXY** [comment]
Yes, initial loading is a bit longer but, IMHO, not really disturbing

**Comment by jjnj023** [comment]
Indeed, nothing to worry about. Maybe in the future store the switch in the app if that is possible.
