### ISSUE TITLE
Camera issues

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#128]
forum member reported:

I can select it but there is no picture.

the camera function is working right on my lan but not outside.
the camera ip in domoticz is 192.168.0.8
is that the problem? that the app connect throught the local IP instead of the domoticzs and then trhoufht local?

**Comment by galadril** [comment]
Thats the problem indeed.. can't work arount it.. Unless Domoticz got changed so that you can configure a outside and inside ip within Domoticz per camera....

**Comment by RoadXY** [comment]
No that will not work since you'll have to open up an NAT port on your router for every camera.

The only way to do this is to have an VPN connection to your local network.

**Comment by galadril** [comment]
we could only show the camera page when he's connected to local network (to avoid confusion)

**Comment by RoadXY** [comment]
I agree.
Just to be clear: in the JSON response you receive cameras with their internal address?
I don't have any cameras so I can't test.

**Comment by galadril** [comment]
There is only one address for a camera in Domoticz..
Those are also the exact fields that I get from the JSON:

So i can't do anything about this issue..

![untitled](https://cloud.githubusercontent.com/assets/14561640/12015815/3b6e63c6-ad42-11e5-89aa-628752bea978.png)

**Comment by RoadXY** [comment]
No, nothing we can do about it then.
