### ISSUE TITLE
Icons and colored buttons

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#129]
frm forum member:

And some icon is not good for switches. 
Example switch wake on lan.
Button log, timer, day, month, year better color will be dark... maybe gray or dark blue. 
Bright gree is no good.

(I can confirm this,  my telephone (oneplusone) are displaying this colour to bright so I can barely see that it's an button)    maybe a small icon is better.

**Comment by galadril** [comment]
"And some icon is not good for switches." >
Not really clear on what needs to be checken? 
only wake on lan? 
Is this related to people having custom iconsz?

**Comment by RoadXY** [comment]
For the buttons colors: Mark has an Nexus 5, my wife an Nexus 4, which both have an LCD and my Nexus 6 is amoled.
Neither of us has what your describing.

My brother has an Oneplus One and I'll check this afternoon to see how this looks.

**Comment by galadril** [comment]
Changed the button color to grey
https://github.com/galadril/DomoticzForAndroid/commit/09757a8371f7d89b637d86e2b12132f7d49850bd
