### ISSUE TITLE
Sorting devices

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#14]
It would be handy to sort devices like:
- status (first on then off)

**Comment by RoadXY** [comment]
As a default for all devices you mean?

**Comment by galadril** [comment]
Think we should implement better sorting:
- order set in Domoticz
- name
- on/off

**Comment by remb0** [comment]
indeed galadril.   sometimes you want to search for a letter,  sometimes you want to know what's on, so you can turn it all off.

**Comment by RoadXY** [comment]
Custom sorting?
But that would require a lot of code to get it working properly.
Like when an device is added on Domoticz, how would you handle that.

**Comment by galadril** [comment]
Would be great if Domoticz could handle the sorting:
http://92.110.168.68:847/json.htm?type=devices&filter=light&used=true&order=Name
http://92.110.168.68:847/json.htm?type=devices&filter=light&used=true&order=Order (specified in Domoticz)
http://92.110.168.68:847/json.htm?type=devices&filter=light&used=true&order=Data
http://92.110.168.68:847/json.htm?type=devices&filter=light&used=true&order=Status (on.off)

Think that we should first ask for this feature there..
When that;s implemented we'll continue on this..

**Comment by RoadXY** [comment]
@galadril Please remove your external IP adres!

**Comment by galadril** [comment]
Thanks

**Comment by galadril** [comment]
I've implemented on/off/all filtering for dashboard, scenes and switches in the next version.
Think that that would be enough for this case right??

See screenshots:
![screenshot_20151208-114906](https://cloud.githubusercontent.com/assets/14561640/11653929/06ad2686-9da2-11e5-8cec-dc849b53b9ab.png)
![screenshot_20151208-114912](https://cloud.githubusercontent.com/assets/14561640/11653930/06bad650-9da2-11e5-9905-a52c00fd7406.png)
![screenshot_20151208-114917](https://cloud.githubusercontent.com/assets/14561640/11653928/06ac801e-9da2-11e5-9d58-c42488a4c408.png)

**Comment by RoadXY** [comment]
Nice!
Where all is alphabetically?

**Comment by galadril** [comment]
yes

**Comment by RoadXY** [comment]
Cool. I can imagine that some user would like this.
Is this setting persistent between app starts?

**Comment by galadril** [comment]
No, all is default. 

then you can choose later via the menu button if you want to see switches that are on, or off..

**Comment by RoadXY** [comment]
Seems logical.
Else users might miss switches when they forgot about the filter.

**Comment by remb0** [comment]
great work! the On filter is good!   but my doorbell gives always only the on button :)    so it's a false candidate to be in the On list.

**Comment by RoadXY** [comment]
Is it a real problem of it's in the list?

**Comment by galadril** [comment]
At this moment all the non-on/óff switches (like push on button, etc) don't have an on or off status.
I threat these switches as being 'on'. That's why their always on 'on'.

Should i always threat them as off? Because they don't have an on/off state...

**Comment by galadril** [comment]
I've added the next filters: 
- on
- off
- static
- all

v0.1.149
