### ISSUE TITLE
Log - Usage log not working

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#140]
When i want to see the log off wattage usage from my christmas light i get the error message:
could not get Log for: Lichtstreng Electric. 

http://domoticz.com/forum/viewtopic.php?f=37&t=8884&sid=61872278123c0d60e71916d8db08fafd&p=67058#p67020

**Comment by galadril** [comment]
I've asked Jango the next information about this issue:

Can you send me the json result of:
http://domoticz_ip:port/json.htm?type=devices&filter=all

And if you open the Domoticz in Firefox, then go to the screen where you see your usage.
- Hit F12 to open de developers console, and make sure the tab 'console' is open.
- Please send me the url that is now in the developers console like:
  "http://ip:port/json.htm?type=textlog&idx=198" or
  "http://ip:port/json.htm?type=graph&sensor=counter&method=1&idx=58&range=day"
- Please also send me the json for that url.

**Comment by galadril** [comment]
After investigation:
The logfile is to large. Your message contains 134677 characters. The maximum number of allowed characters is 60000.

We need to check if this is a Domoticz issue.. and the api should only show the top 100??

**Comment by RoadXY** [comment]
Did you comment here @galadril
