### ISSUE TITLE
Set color for dimmable light

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#141]
It's not possible to set the color of a RGB lamp from the Dashboard.
It is actually implemented in the switch fragment!

http://domoticz.com/forum/viewtopic.php?f=37&t=8884&sid=61872278123c0d60e71916d8db08fafd&p=67058#p67080

**Comment by galadril** [comment]
To debug the issue your collored lights, can you send me the json result of:
http://domoticz_ip:port/json.htm?type=devices&filter=all

And if you open the Domoticz in Firefox, then go to the screen where you see your lights.
-    Hit F12 to open de developers console, and make sure the tab 'console' is open.
-    Change a color of one of you lamps
-    Please send me the url that is now in the developers console like:
  "http://92.110.168.68:847/json.htm?type=command&param=setcolbrightnessvalue&idx=112&hue=205&brightness=82&iswhite=false" 
-    Please also send me the json result for that url.

**Comment by galadril** [comment]
After investigation:
- we can set the color from the switch page
- we can't set the color from the dashboard.. (so thats the issue!!!!)

**Comment by RoadXY** [comment]
Cool, nice find!

**Comment by galadril** [comment]
Closed in next version
