### ISSUE TITLE
Dimmer slider too small

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#146]
the slider of the Dimmer get's pushed away by the Data field.

http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=67169#p67169

**Comment by RoadXY** [comment]
![0](https://cloud.githubusercontent.com/assets/3482284/12034707/2475283c-ae35-11e5-828f-250a2a72090c.png)

**Comment by galadril** [comment]
Fixed in next version!
