### ISSUE TITLE
Action Send port hardcoded

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#147]
By ehallq: So it looks like the "send port" is hard coded to 8080 and that the user specified port is only used when reading.

We need futher investigation on this matter!

http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=67166#p67166

**Comment by RoadXY** [comment]
I don't believe it's true but I can test real easy trough a port mapping on my router.

**Comment by RoadXY** [comment]
Can you assing this one to me? :p

**Comment by galadril** [comment]
(cant add you...??) I only see mee in the Assignee list..

**Comment by RoadXY** [comment]
Crap, then I'll probably need more rights.
Never mind then.

**Comment by RoadXY** [comment]
Checked:
- Set app to port 8088
- Added a NAT port forwarding on 8055
- Checked if connection would timeout -> it did
- Changed app to 8055 and deleted port 8088 in router
- tried several switches -> all worked
- Changed app back to 8088 (while router still on 8055) -> timeout
- Changed the router back to 8088 -> all working again

Either way: 8080 is not hardcoded!
