### ISSUE TITLE
Dimmer - values not correct

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#148]
By ehallq:
When dimming my fibaro dimmer 2, I get a response of the dimming value set to +1 over the actual value (if i dim to 100%, the message says 101., 53 gets 54 etc.) If I then turn it off with the button, and then on again with the button I would want it to set to the last value or full, as for now the app shows a random percentage each time turning on and off (using the button, not the slider).

http://domoticz.com/forum/viewtopic.php?f=37&t=8884&p=67200#p67199

**Comment by galadril** [comment]
in the adapter code:
handleDimmerChange(mDeviceInfo.getIdx(), progress + 1);

**Comment by RoadXY** [comment]
Yeah, but else the value wasn't correct and in line with Domoticz server.
That's why

**Comment by galadril** [comment]
ah, i see!

**Comment by galadril** [comment]
"as for now the app shows a random percentage each time turning on and off (using the button, not the slider)."

This is probably returned by Domoticz json? We don't just come up with a random number :)

And i don't see this happening for my 6 lights...?

**Comment by RoadXY** [comment]
I think we need access to his server, I'll ask

**Comment by galadril** [comment]
think we need more then viewer rights...

**Comment by RoadXY** [comment]
http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=67466#p67435

by pepeEL » Thu Dec 31, 2015 1:07 am

I found next bug. On my Fibaro RGBW FGRGBWM-441 when i set level i have other level above slider and other in text. It show ok after refresh app or close and opern again. And in text "level" is double see.

![screenshot_2015-12-30-23-49-21](https://cloud.githubusercontent.com/assets/3482284/12063036/de7c12fe-afa7-11e5-858a-70bb8e6c4f3f.jpg)
