### ISSUE TITLE
 Widget add Category in Configuraton Activity

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#149]
Postby ehallq » Tuesday 29 December 2015 13:44

When choosing a widget I have a switch called "Rummet" and a thermometer also with the name "Rummet". When choosing between them you wil have to guess which one to be a switch or thermometer, you could maybe add categories?

http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&p=67186#p67186

**Comment by RoadXY** [comment]
Isn't the icon already an sort of category?

**Comment by galadril** [comment]
I'm talking about the widget configuration screen:

**Comment by RoadXY** [comment]
got it, sorry

**Comment by galadril** [comment]
wilde nog een screen posten :)
![screenshot_20151229-142039](https://cloud.githubusercontent.com/assets/14561640/12034970/06e87e92-ae38-11e5-835a-609c9d1d3eae.png)

**Comment by galadril** [comment]
I think this will do: 
![screenshot_20151229-150329](https://cloud.githubusercontent.com/assets/14561640/12035465/85ec3b84-ae3d-11e5-86d0-ef02db6c4243.png)

**Comment by galadril** [comment]
Or should i put in values like: "Utilities" "Switch" "Weather"?
Those are values that i don't get in the json results...

**Comment by galadril** [comment]
Think it's fixed this way right?
![screenshot_20151229-160041](https://cloud.githubusercontent.com/assets/14561640/12036351/856e2bd8-ae45-11e5-90a7-6a8a231cf5c7.png)

**Comment by RoadXY** [comment]
I think, for now, this is great.
Fancy improvements later.

**Comment by galadril** [comment]
better this way..

![1](https://cloud.githubusercontent.com/assets/14561640/12062479/c8be9a4a-af9d-11e5-9b58-d54289265c6b.png)
![2](https://cloud.githubusercontent.com/assets/14561640/12062478/c8bbe336-af9d-11e5-8c9d-bcdcb051783f.png)
