### ISSUE TITLE
hide data and last seen.

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#15]
Option to hide:
data and last seen.

My wife doesn't care, it would be cleaner

**Comment by RoadXY** [comment]
We could move last seen to the onLongClick

**Comment by remb0** [comment]
nice option indeed.  less scrolling and most of the time not needed.

**Comment by RoadXY** [comment]
I agree

**Comment by galadril** [comment]
A possibility to show a minimal dashboard is added in v0.1.134:
That should be a good solution for making the Dashboard less crowded..

![screenshot_20151120-102728](https://cloud.githubusercontent.com/assets/14561640/11296318/bb2d41ac-8f71-11e5-99b1-21cdf3300bed.png)
![screenshot_20151120-102720](https://cloud.githubusercontent.com/assets/14561640/11296319/bb313b72-8f71-11e5-8c08-caa15daa195e.png)

**Comment by RoadXY** [comment]
Nice!

**Comment by galadril** [comment]
That would be enough to Close this case??

**Comment by RoadXY** [comment]
I agree, looks nice this way.
Maybe there could be more things done to enhance the layout but in my opinion that's something for later when the app is released.
@remb0 What do you think?

**Comment by remb0** [comment]
Yes indeed   great work!    cleaner / less scrolling and my wife isn't overwhelmed with info :p
Thanks!
