### ISSUE TITLE
merging thermostat set en actual

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#16]
I have an icy e-thermostat and have 2 devices: 1 to set the themperature, and one to see the current temperature.

**Comment by galadril** [comment]
Are those two devices in Domoticz?

**Comment by remb0** [comment]
yes indeed:
    88  Thermostaat 0000001 0   Thermostaat_Set Thermostat  SetPoint    17.0    -   -   Set UnusedRename Device Log 2015-11-25 21:26:30
    89  Thermostaat 0001    1   Thermostaat Temp    TFA 30.3133 20.5 C  -   100 Set UnusedRename Device Log 2015-11-25 21:26:30

also in domoticz it isn't nice ;) because 1 device is at temperatures and 1 in utilities. :P
But this is low prio

**Comment by galadril** [comment]
I'm not really in favor of changing the domoticz logic (which gives me two devices)..

**Comment by RoadXY** [comment]
I'll have to agree with @galadril on this.
If Domoticz changes some things it could break the support for this devices.
