### ISSUE TITLE
Add to translation

### ISSUE THREAD

**Issue by ghost** [galadril/DomoticzForAndroid#169]
In file strings_plans.xml should be add string to value devices from 2 to 4(to translation):

<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation">

```
<string name="title_plans">Plans</string>
<plurals name="devices">
    <item quantity="one">%1d device</item>
    <item quantity="2-4">%1d devices</item>
    <item quantity="other">%1d devices</item>
</plurals>
```

</resources>

Polish translation:
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation">

```
<string name="title_plans">Plans</string>
<plurals name="devices">
    <item quantity="one">%1d urządzenie</item>
    <item quantity="2-4">%1d urządzenia</item>
    <item quantity="other">%1d urządzeń</item>
</plurals>
```

</resources>

**Comment by RoadXY** [comment]
2-4 is not possible.
I think we should change the text to:
Devices: 1

instead of:
1 device
2 devices
4 devices
etc

**Comment by ghost** [comment]
OK no problem.

But i know that in Android it is possible. I use project TVHClient and developer this app include translation for One program , 2-4 programs and more programs...

Looks on translation Polish:
https://github.com/rsiebert/TVHClient/blob/develop/res/values-pl/plurals.xml

**Comment by galadril** [comment]
Think we can close this issue
