### ISSUE TITLE
Add Radius to Geofencing

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#17]
add radius/marge to the geofencing location.

**Comment by galadril** [comment]
Added to v0.1.137

![screenshot_20151124-091301](https://cloud.githubusercontent.com/assets/14561640/11361189/efc00374-928b-11e5-9758-1e0d18b3f64b.png)
![screenshot_20151124-091255](https://cloud.githubusercontent.com/assets/14561640/11361188/efbfd0ca-928b-11e5-97ec-d3cf71aac080.png)

**Comment by RoadXY** [comment]
This is in meter, right?
Could that be added behind the number to clarify things?
