### ISSUE TITLE
Swipen

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#176]
Een sterke toevoeging zou in mijn optiek zijn als je kunt swipen tussen de zogenaamde tabbladen. Dus vanaf Scenes een veeg naar rechts voor het Dashboard en een veeg naar links voor de Switches.

een bericht van gonadan (tweakers)

**Comment by RoadXY** [comment]
IMHO: no.
That's against Google's recommendations.
Than we should have used tabs but that would mean a lot of more scrolling.

Plus every fragment is going to refresh onCreate so it wouldn't be fast either.

**Comment by remb0** [comment]
koppel ik terug.

**Comment by galadril** [comment]
Im also against swiping if you use a navigation menu..

**Comment by RoadXY** [comment]
Close, I guess?
