### ISSUE TITLE
Lay-out tips

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#18]
- less scrolling. (menu, in device lists everywhere)
- the place of logo, domoticz and the link  it uses to much space.
- use icons for  log/ timer and notification (language independent, cleaner)
- Gas/water/energie icon is not correct.
- domoticz icon on dashboard is a square instead of the transparant icon.

**Comment by RoadXY** [comment]
Could you clarify that please?
Maybe with a screenshot?

**Comment by galadril** [comment]
"less scrolling. (menu, in device lists everywhere)"
Isn't this a matter of tast? I don't like everything all pushed and squeezed in one tight spot

**Comment by RoadXY** [comment]
And the search function works great

**Comment by remb0** [comment]
Point taken ;)

**Comment by RoadXY** [comment]
Could you please take a screenshot of the icon issues?

**Comment by galadril** [comment]
"Gas/water/energie icon is not correct."
is now handeld by this issue: #75 

Im closing this issue!
