### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#187]
Links naar playstore.

**Comment by RoadXY** [comment]
Die zijn er al?
Die zwarte, grote knoppen :-p

**Comment by galadril** [comment]
lol

**Comment by remb0** [comment]
This is a Android for Domoticz and will soon be in the Play Store (not
ready yet)

doelde ik meer op!  sorry :)

Met vriendelijke groet,

Remco van Geel

2016-01-02 23:15 GMT+01:00 Mark Heinis notifications@github.com:

**Comment by RoadXY** [comment]
Done.
Yesterday we moved to the official Domoticz github page:
https://github.com/domoticz/domoticz-android/blob/master/README.md
