### ISSUE TITLE
About screen (a sub option under settings)

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#20]
- credits
- link to domoticz / github / android app topic
- version info

**Comment by RoadXY** [comment]
I agree, credits (for the libraries used) is needed and would give a cleaner look

**Comment by galadril** [comment]
So what should be exact on the about page ?
Think we could do credits for libraries on this github readme..

**Comment by RoadXY** [comment]
About is about Domoticz and maybe GPL?

Credits is about the libraries used, people who helped and off course the developers ( :-D )

**Comment by galadril** [comment]
Nice one

**Comment by RoadXY** [comment]
Version one: https://github.com/galadril/DomoticzForAndroid/pull/111
