### ISSUE TITLE
Applamp/Limitled rgbw lights are crashing

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#21]
lamp 1 2 3 and group_all are displayed but can't controlled.
the app crashed after switching

**Comment by RoadXY** [comment]
Could you create a screenshot please to make things more clear?

**Comment by remb0** [comment]
I have send the debug log.
applamp is a rgbw from mi-light.

**Comment by galadril** [comment]
Can you add the debug log here?

**Comment by remb0** [comment]
doesn't crash anymore.   I can turn it on and dim whitout issues!
maybe choosing a color is a new issue woth (a feature reqeust)   I will close this issue,
