### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#22]
An widget editor would be nice.
where you can choose devices/options and layout.

It would be faster then opening apps most of the time.

**Comment by RoadXY** [comment]
An widget for one device to control or see you mean?

**Comment by remb0** [comment]
maybe the option to choose a few kinds of widgets (1x1, 4x1  4x2  etc.  and choose you own devices for that widget.

**Comment by galadril** [comment]
Building some resizable widgets...
What do you think of them??

![widgets](https://cloud.githubusercontent.com/assets/14561640/11715354/8b378fea-9f41-11e5-94b9-96114ea57364.png)

**Comment by RoadXY** [comment]
What does Go do?

**Comment by galadril** [comment]
Toggle a switch (nothing right now, but working on it ;) )
Was just a first screenshot

**Comment by RoadXY** [comment]
Ah, I see, sorry :-)

**Comment by galadril** [comment]
Added in v0.1.151 (probably still some bugs in!!)

![index](https://cloud.githubusercontent.com/assets/14561640/11748422/810aa862-a028-11e5-95e8-7f4b77f8013d.png)

**Comment by RoadXY** [comment]
Could you update the source? Maybe going to work on Geo tonight

**Comment by galadril** [comment]
Did you liked the widgets??

**Comment by galadril** [comment]
Then i'll close this case

**Comment by remb0** [comment]
some ideas for the widgets:
- background chooser (a colour or in my case transparant)
- can the On button be replaced with the only the icon?
  when the widget is smaller, the On button is over the text of the widget.  and when the logical (on/off) is only on the icon the widget can be much smaller.
- I think you might refer to widgets in the app.

**Comment by RoadXY** [comment]
Actually, I really like them. They are resizeable so if you make them a bit wider all is fine!

I do have some suggestions though:
- When clicking on them (not the switch) I think it would be nice to open Domoticz?
- There not always updated but havent found out when exactly
- Name isn't updated when changed in Domoticz
- Unclear what the update frequency is (Maybe a setting?)

**Comment by galadril** [comment]
Update frequently can't be lower then 30 minutes (defined by Google)..

**Comment by remb0** [comment]
otherwise it will drain battery and higher your databundle ?

Met vriendelijke groet,

Remco van Geel

2015-12-14 12:03 GMT+01:00 Mark Heinis notifications@github.com:

**Comment by galadril** [comment]
yes
