### ISSUE TITLE
import/export settings 

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#23]
Handy when you have multiple devices (gsm,gsm2, tablet, media box, etc)

export to gmail/dropbox/local storage etc.

**Comment by RoadXY** [comment]
You'll have to keep all devices up to date manually.
I don't think there are many settings and the ones which are there are easy to setup.

**Comment by galadril** [comment]
Sorry, but an Android app is not a Domoticz replacement.. I really think that settings, adding hardware/devices, etc should be done on the Domoticz Portal...

**Comment by remb0** [comment]
I mean not the domoticz settings (you are right for that)  I mean:  geofencing/connection settings etc  real domoticz app settings.

**Comment by galadril** [comment]
Good idea.. (also handy for us developers + testers, that need to install the app too many times :) )
Implemented in v0.1.134

![screenshot_20151120-090011](https://cloud.githubusercontent.com/assets/14561640/11294671/9a484fec-8f65-11e5-9a58-714a61ee180e.png)
![screenshot_20151120-084308](https://cloud.githubusercontent.com/assets/14561640/11294672/9a4aeef0-8f65-11e5-907a-642d093c2a26.png)

**Comment by RoadXY** [comment]
When targeting API 23, all settings are restored automatically by Android.
Maybe take this into account?

**Comment by galadril** [comment]
I already had a method (for another app) to write the whole SharedPreferences to a file.
So it was easy to implement..

**Comment by RoadXY** [comment]
Lol, that makes it a lot easier I guess!
