### ISSUE TITLE
Helping wizard

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#24]
Every now and then a pop-up message should appear if a user hasn't used a specific function since the installation of the app.
Think of things like the long press on a device to get extra info, the geofencing etc

**Comment by galadril** [comment]
I've already worked for another project with ShowCaseView to implement this logic:
https://github.com/deano2390/MaterialShowcaseView

**Comment by RoadXY** [comment]
I'm familiar with this one as I have used it in my other project.
However, how are we going to tell about, for example, the Geofence feature (which I think is a nice feature all users should know about)

**Comment by remb0** [comment]
I think first time using wizzard.
I think that wizzard must also be startable from settings (is you want to refresh your knowlege)

but a popup now ans then can be irritating.. :P so it must be switchable and overthinked.

**Comment by RoadXY** [comment]
I was thinking of something in the line of the below "Got it" cards, like Google does, for the Geofence setting.
Other settings through Showcaseview.
Any thoughts on this?

![get-quick-access-almost-any-system-function-your-android w654](https://cloud.githubusercontent.com/assets/3482284/11318925/3f144da4-9066-11e5-820f-bf4baacca9a6.jpg)
![nexus2cee_tips](https://cloud.githubusercontent.com/assets/3482284/11318926/5c706982-9066-11e5-89bc-e50d41c1cdd9.png)

**Comment by galadril** [comment]
I think it would already help to guide the user a bit more with some action snackbars, to show what he is doing.

Ill look into these cards later!

![screenshot_20151126-095815](https://cloud.githubusercontent.com/assets/14561640/11418924/7db929c8-9424-11e5-83a5-98b2b027aec4.png)

**Comment by galadril** [comment]
You could also add buttons or swipe actions to a Snackbar, so for example:
- When the user shows the Dashboard for the first time
    Show snackbar with:
  - text: Long-click on a Switch for adding favorites 
  - button: N/A
- When user opens the app for 10-th time, but no Geofence configured (and snackbar not shown earlier, to prevent spamming)
  - text: Would you like to setup Geofencing?
  - button: Yes!
  - action button opens Geofence settings page

and so on..
Think this would be a nice solution to guid a user!

**Comment by galadril** [comment]
See here a Snackbar with button:
https://lokeshcodes.files.wordpress.com/2015/09/12.png?w=440

**Comment by galadril** [comment]
And I do think that you don't have to guide a user to mutch.. Users should also explore apps on there own (which gives a feeling of accomplishment)!

Most of the apps in the play store only show some important features, nothing more..

Or only show a hint if the feature is never used (after 10 days of using the app)

**Comment by RoadXY** [comment]
I agree on the snackbar idea and the 'not much guiding the user'!
After 10 days of use seems like a valid timeout

My point was: we should tell the user the app has more awesome features then only the drawer ;-)

**Comment by galadril** [comment]
I think i've nailed this issue!
![1](https://cloud.githubusercontent.com/assets/14561640/11783925/f7852154-a279-11e5-8645-7fec10ad5dd1.png)
![2](https://cloud.githubusercontent.com/assets/14561640/11783929/f9410e2c-a279-11e5-98e0-f2d1515fedfb.png)

The last help card is to assist the user, to remove the wizard from the navigation menu via settings :-)

![3](https://cloud.githubusercontent.com/assets/14561640/11783943/0c1e329a-a27a-11e5-97d7-289b67d0b1c1.png)

**Comment by RoadXY** [comment]
WTF dude! Great work!
Show me the code! :-D
