### ISSUE TITLE
Android ware optimalisations

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#25]
what's the criteria for the devices that are available on the watch?
not all my devices are displayed.

I think it would be handy or to choose devices or use plans.

The scrolling should be minimized.

**Comment by RoadXY** [comment]
Domoticz on my Android Wear device isn't working at all.
I have a LG G Watch (1st gen LG Wear device, square)

**Comment by galadril** [comment]
Android Wear version?

**Comment by galadril** [comment]
"The scrolling should be minimized. "
I use the default scrolllist with default spaces.
These are also used in the app-drawer of Android Wear (5.1.1) itself.

Is has the space for 1 item upperpart of the screen, 1 in the middle and 1 on the bottom.

**Comment by RoadXY** [comment]
Latest and greatest baby :-D

**Comment by galadril** [comment]
@RoadXY What's not working? You don't have the app on your watch (not auto installed?), or does it crash?

**Comment by RoadXY** [comment]
@galadril see here
Tried several things like reboot Wear device, reinstall Domoticz.

https://youtu.be/4RH7RJV7ilk

**Comment by RoadXY** [comment]
This is the debug output

```
11-20 12:24:40.446 7157-7157/nl.hnogames.domoticz D/WEARDEVICE: onConnected null
11-20 12:24:40.446 7157-7157/nl.hnogames.domoticz D/WEARDEVICE: Send: 
11-20 12:24:40.498 7157-7678/nl.hnogames.domoticz V/WEARDEVICE: Message: {my object} sent to: Nexus 6
```

**Comment by galadril** [comment]
The watch requests the info from the phone.. so it sends a emty request to the phone:
D/WEARDEVICE: Send: 

But it seems that the app on the phone never returns the values..

That mechanism works pretty good on my Moto 360, can you debug/trace this issue ??

**Comment by RoadXY** [comment]
Ok, found the problem.
It's in this part:

WearMessageListenerService.java

```
        if(supportedSwitches.size()>0)
        {
            String parsedData = new Gson().toJson(supportedSwitches);
            Log.v(TAG, "Sending data: "+parsedData);
            sendMessage(SEND_DATA, parsedData);
        }
```

Appears I don't have any supported switches on my dashboard because supportedSwitches.size() = 0, lol.

Anyway, there is no else function in the above code which will handle the situation where there aren't any supported switches and that's why only the splash screen shows.

**Comment by galadril** [comment]
Great.. yeah that handling should be improved!

Do you think I should show all switches?
Now I only show switches that are favorite..
Or should this be a setting...

**Comment by RoadXY** [comment]
Let me check a few things because as far as I remember I do have favorite switches for my garden lights.
I'll come back on this.

**Comment by RoadXY** [comment]
Ok, I'm an idiot.
I didn't had any devices as favorite.

It's working now.
However the issue still stands: there should be a follow up screen explaining the user how to get the devices on his wearable.

![wear - devices](https://cloud.githubusercontent.com/assets/3482284/11299902/fb3c918a-8f8a-11e5-9be9-2aca74e0cff0.png)

**Comment by galadril** [comment]
Do you think I should show all switches?
Now I only show switches that are favorite..

or maybe a setting?

**Comment by RoadXY** [comment]
I'm a bit changing my thoughts between:
- asking the user on his wearable 
- just explaining the user how he can get his devices on his wearable

**Comment by RoadXY** [comment]
No one ever goes to settings to check what options are available.
We have to guide them somehow.

**Comment by galadril** [comment]
We have a case for that matter:
https://github.com/galadril/DomoticzForAndroid/issues/24

**Comment by RoadXY** [comment]
Your right. Now on to the question of Remb0: should users be able to select somehow which devices show up on there wearable.
I think it should.

**Comment by remb0** [comment]
I agree.  the watch is to tiny to display all my 100 devices.  and some devices are not important and i will never switch them on my watch.
but some devices across multiple plans I will control from my watch.    so I think a user must go to settings > wearables and configure that themself.    users with domoticz + watch are capable of doing that.

but we can also use the sliding to different plans on the watch?

**Comment by RoadXY** [comment]
That's quite a lot of work.
Switching on from a selection might be doable though.

**Comment by RoadXY** [comment]
Regarding my issue, this solved it:
https://github.com/galadril/DomoticzForAndroid/pull/32

**Comment by galadril** [comment]
Great work!

**Comment by RoadXY** [comment]
Not the prettiest solution but I'm sure we'll come up with something nicer later on.

**Comment by galadril** [comment]
I've also added the possibilty to choose your custom switches..
Closing this case..

Added in v0.1.136!
Screenshots:
![screenshot_20151123-120104](https://cloud.githubusercontent.com/assets/14561640/11335149/29ce2ad0-91da-11e5-8bf6-464c1a2bb1ef.png)
![screenshot_20151123-120112](https://cloud.githubusercontent.com/assets/14561640/11335148/29cad664-91da-11e5-9c0a-b24e2bf2259e.png)

**Comment by RoadXY** [comment]
BAM!

**Comment by galadril** [comment]
:+1:

**Comment by remb0** [comment]
Nice!!   Echter klik ik 20 devices aan. 
Deurbel  
On/off
Scene alles
En wat dimmers    

Maar krijg lang niet alles te zien.   De deurbel en 3 kaku switches.    Hoe kan ik debug info leveren?

**Comment by galadril** [comment]
https://github.com/galadril/DomoticzForAndroid/blob/master/app/src/main/java/nl/hnogames/domoticz/Domoticz/Domoticz.java

I've only added the next Wear supported switches..
But I show all the switches in the Dialog :-)

I should filter the dialog also for supported switches!

public List<Integer> getWearSupportedSwitchesValues() {
        List<Integer> switchesSupported = new ArrayList<>();
        switchesSupported.add(Device.Type.Value.ON_OFF);
        switchesSupported.add(Device.Type.Value.PUSH_ON_BUTTON);
        switchesSupported.add(Device.Type.Value.PUSH_OFF_BUTTON);
        switchesSupported.add(Device.Type.Value.MEDIAPLAYER);
        switchesSupported.add(Device.Type.Value.SMOKE_DETECTOR);
        switchesSupported.add(Device.Type.Value.X10SIREN);
        switchesSupported.add(Device.Type.Value.DOORLOCK);
        switchesSupported.add(Device.Type.Value.DOORBELL);
        return switchesSupported;
    }

**Comment by galadril** [comment]
I've added the check for supported wear devices in v0.1.137
Please check if it works beter (when update is available in store)

**Comment by remb0** [comment]
ahhi understand.  all my light are dimmable of rgb's  that's why the don't show in selector and also not on watch.

**Comment by jjnj023** [comment]
It looks like it has been designed with the flat tire screen of the Moto is mind. On other round watches it looks strange to have a full screen while scrolling at the top but a 'cut' at the bottom.

**Comment by galadril** [comment]
Can you make screenshots?

**Comment by jjnj023** [comment]
![screen](https://cloud.githubusercontent.com/assets/7522820/11503152/44c5ff5a-983f-11e5-8b34-cec3895c1062.png)
Here you go. As you can see the top will continue as a screen the bottom part is 'cut'.
Also you can see in the screenshot some devices show a dimmer value, these switches however are on/off switches and not dimmers.

**Comment by RoadXY** [comment]
These 'fake' dimmers are correctly displayed in the app?

**Comment by jjnj023** [comment]
A now I see, the app itself has the same issue here.

**Comment by galadril** [comment]
I dont really know if it's an issue of the app, because Domoticz give me that data...

**Comment by jjnj023** [comment]
In domoticz it is shown as a regular on/off switch.

Back to on topic.
It would be nice to be able to switch scenes as well, since most things I do with domoticz are switching scenes or groups.

**Comment by RoadXY** [comment]
Yes, please create a separate issue for the switch issues please

**Comment by RoadXY** [comment]
Switching scenes is already supported?
![screenshot_20151201-163910](https://cloud.githubusercontent.com/assets/3482284/11505383/6c5489e6-984a-11e5-9744-e3e9231197f7.png)

**Comment by galadril** [comment]
No, at this moment only some switches.
See post earlier:

switchesSupported.add(Device.Type.Value.ON_OFF);
switchesSupported.add(Device.Type.Value.PUSH_ON_BUTTON);
switchesSupported.add(Device.Type.Value.PUSH_OFF_BUTTON);
switchesSupported.add(Device.Type.Value.MEDIAPLAYER);
switchesSupported.add(Device.Type.Value.SMOKE_DETECTOR);
switchesSupported.add(Device.Type.Value.X10SIREN);
switchesSupported.add(Device.Type.Value.DOORLOCK);
switchesSupported.add(Device.Type.Value.DOORBELL);
switchesSupported.add(Device.Type.Value.DIMMER);

**Comment by jjnj023** [comment]
For Android Wear
Op 1 dec. 2015 4:41 PM schreef "Robin van Kekem" notifications@github.com:
