### ISSUE TITLE
Reload MainActivity after changing setting

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#27]
Reload MainActivity after opening/closing the Setting screen

**Comment by RoadXY** [comment]
Lol, I have been fighting with this in the past and thought about doing it later, lol

**Comment by RoadXY** [comment]
startActivityForResult maybe?

**Comment by galadril** [comment]
Yep...
Like I've done for the Welcome screens :)

**Comment by RoadXY** [comment]
Sometimes the solution is so simple it doesn't come up, lol

**Comment by galadril** [comment]
Fixed in v0.1.135
