### ISSUE TITLE
Dashboard - Add long press menu

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#28]
Since all other screens do have it I miss it there

**Comment by galadril** [comment]
Implemented in v0.1.135
![screenshot_20151120-154558](https://cloud.githubusercontent.com/assets/14561640/11302467/fb5b040e-8f9d-11e5-99e0-b00a998d2f93.png)

**Comment by RoadXY** [comment]
Wtf, dude take a break haha

**Comment by galadril** [comment]
Oke ,ill will :+1:
