### ISSUE TITLE
Welcome wizard - server settings, not clear there are more settings, ie Nexus 4

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#3]
![welcome wizard - more options](https://cloud.githubusercontent.com/assets/3482284/11256399/fa9c601a-8e4b-11e5-8b7b-dcfacb36ae7a.png)

**Comment by galadril** [comment]
Should be fixed in v0.1.133

**Comment by RoadXY** [comment]
Nice!

**Comment by RoadXY** [comment]
Scroll bar permanently visible. Fine solution, I think.

![welkom wizard nexus 4](https://cloud.githubusercontent.com/assets/3482284/11274709/6211d8a4-8eda-11e5-939a-ca48e829b048.png)
