### ISSUE TITLE
Graphs - For various devices

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#30]
No further explanation needed, I guess

**Comment by galadril** [comment]
I'm looking into making the graph's, but it's hard to find a pattern in the json urls for specifying the sensor.

---

Info of Urls:
Weather:
/json.htm?type=graph&sensor=temp&idx=47&range=day
/json.htm?type=graph&sensor=temp&idx=47&range=month
/json.htm?type=graph&sensor=temp&idx=47&range=year

Some Utilities:
/json.htm?type=graph&sensor=Percentage&idx=4&range=day

Zicht:
/json.htm?type=graph&sensor=counter&idx=50&range=day

UV:
/json.htm?type=graph&sensor=uv&idx=49&range=day

Url splitted:
base: /json.htm?type=graph
sensor: &sensor=temp
id of sensor: &idx=47
range (day month year): &range=year

---

My question is how to determine the sensor type that we're using for getting the graph data...

**Comment by galadril** [comment]
It looks like I don't get the graph sensor type back in the device json result /json.htm?type=devices.
for example, Zonnepannelen are from the graph type 'counter'.

But here is the device result:

{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CounterToday" : "4.000 kWh",
         "CustomImage" : 0,
         "Data" : "2283.000 kWh",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 5,
         "HardwareName" : "Ginlong",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "00014089",
         "LastUpdate" : "2015-11-26 14:00:05",
         "Name" : "Zonnepanelen",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "kWh",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "current",
         "Unit" : 1,
         "Usage" : "611.0 Watt",
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "58"
      },

**Comment by galadril** [comment]
I've started on working on the Graphs.. I;'ve added graphs to the Temperature screen:

![screenshot_20151129-171833](https://cloud.githubusercontent.com/assets/14561640/11458377/f2b47d9e-96be-11e5-967f-5706ba8da971.png)

![screenshot_20151129-171850](https://cloud.githubusercontent.com/assets/14561640/11458376/f290f694-96be-11e5-9075-430bbcee48b1.png)

**Comment by RoadXY** [comment]
I saw the commit.
Nice initial work!

**Comment by galadril** [comment]
I've also added Graphs for Utilities and Weather:

![2](https://cloud.githubusercontent.com/assets/14561640/11495905/039ca77a-980f-11e5-8d18-1bb1d8c00c5d.png)
![1](https://cloud.githubusercontent.com/assets/14561640/11495906/039cd448-980f-11e5-88f7-48720595b5ab.png)

So far so good :+1:

**Comment by RoadXY** [comment]
Nice!

**Comment by RoadXY** [comment]
I think we just need a legend below the graph

**Comment by galadril** [comment]
Ok

**Comment by RoadXY** [comment]
![screenshot_20151203-094053](https://cloud.githubusercontent.com/assets/3482284/11555639/1356d7b4-99a2-11e5-8ab3-7ee85d455d7c.png)

Example for a legend

**Comment by remb0** [comment]
I got the day month year by all devices also by devices that it do not support.
but by energy I got a message below:
could not get log data for: Energy Energy

**Comment by remb0** [comment]
I also think this must be modular as extra data on dashboard.

**Comment by galadril** [comment]
I would rather not place it on the dashboard, and keep the dashboard (like in domoticz) clean.

Whats the json url when you check the graph for 'Energry' within Domoticz itself?

**Comment by remb0** [comment]
yes i don't mean the dashboard.   but the modulair way we can enable/disable  extra's on the dashboard.   that's also a nice option for graphs.

the Json url in domoticz is: json.htm?type=graph&sensor=counter&idx=2&range=week

**Comment by galadril** [comment]
Why would you like all kinds of settings for enabling and disabling things?

Also in Domoticz on the Dashboard, you don't see log / timer / adjust or graph buttons...
![dashboard](https://cloud.githubusercontent.com/assets/14561640/11591461/4ea7ed98-9a98-11e5-8de9-995c557d1d44.png)

But you do see them on the individual screens:
![switches](https://cloud.githubusercontent.com/assets/14561640/11591522/af75d5fe-9a98-11e5-8da1-f95e6037d560.png)

I'm always a supporter of the KISS principle ("Keep it Simple, Stupid").
https://en.wikipedia.org/wiki/KISS_principle

**Comment by galadril** [comment]
"could not get log data for: Energy Energy"
This is fixed in the next version

**Comment by RoadXY** [comment]
I agree in the KISS part.
That works for the most of the users I'm afriad.

**Comment by galadril** [comment]
Added a legend in the next version (if there are more then one line!)

![screenshot_20151215-114149](https://cloud.githubusercontent.com/assets/14561640/11808955/e9e71c32-a323-11e5-8e5c-a515ce88c404.png)
![screenshot_20151215-115220](https://cloud.githubusercontent.com/assets/14561640/11808956/e9ecb0de-a323-11e5-916e-1e7a09e49c63.png)

**Comment by RoadXY** [comment]
A legend would be a welcomed change

**Comment by RoadXY** [comment]
Damn your fast lol
