### ISSUE TITLE
Icons - Icons on 7" 160dpi tablet borked

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#35]
![screenshot 04_25pm nov 22 2015](https://cloud.githubusercontent.com/assets/3482284/11325651/69a07bd6-9153-11e5-82ed-f9fdc548389e.png)

**Comment by galadril** [comment]
That looks ugly! I don't have a tablet.
I think it would be handy if someone works on this with a tablet..

**Comment by RoadXY** [comment]
I'll check tonight.

**Comment by galadril** [comment]
I've improved the quality of the icons x2 (from 48pixels to 128) in version v0.1.139
Please check how it looks now! (ill wait with closing this case..)

PS i found out that the original (free) icons where from this place:
http://flaticons.org/free-circle-icon-set/

![screenshot_20151125-142707](https://cloud.githubusercontent.com/assets/14561640/11398424/e03270d6-9380-11e5-9796-3abbc6d8b93e.png)
![screenshot_20151125-142656](https://cloud.githubusercontent.com/assets/14561640/11398425/e057e118-9380-11e5-98c1-740bfc38850a.png)
![screenshot_20151125-142703](https://cloud.githubusercontent.com/assets/14561640/11398426/e058b908-9380-11e5-8385-b387f082aed4.png)

**Comment by RoadXY** [comment]
Yeah, I investigated this yesterday and found that there was only one icon for all screen size.
If I let Android Studio create the different size it was better but all icons were smaller.
However the size was not sufficient enough for xxxhdpi

**Comment by galadril** [comment]
Looks better now on your tablet??

**Comment by RoadXY** [comment]
I'll fire up the old Samsung when I get home tonight!

**Comment by galadril** [comment]
Can we close this case???
:8ball:

**Comment by RoadXY** [comment]
Yes

![screenshot_2015-11-29-19-25-09](https://cloud.githubusercontent.com/assets/3482284/11459117/80f0650e-96cf-11e5-9980-6eeda8427d4f.png)
