### ISSUE TITLE
Import settings doesn't also add the GeoFence locations

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#38]
Import settings doesn't also add the GeoFence locations to the GPS system.
We should add all geofences to the google api when importing settings

**Comment by RoadXY** [comment]
I thought export settings did a export to the local storage and not some Google API?

**Comment by galadril** [comment]
Correct, it saves it on your sd storage.
But Importing these settings doesn't add the Geofence locations again to the Google API

**Comment by RoadXY** [comment]
Import to Google API at restore. Got it.

**Comment by galadril** [comment]
Importing settings now also imports the location to the Google API (starts the listener for the Geofences)

Fixed in v0.1.146
