### ISSUE TITLE
Search - overflow menu almost gone on some devices (Nexus 4)

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#4]
![search - overflow menu almost gone](https://cloud.githubusercontent.com/assets/3482284/11256491/6f51d6e2-8e4c-11e5-81a8-d0eb47cd7444.png)

**Comment by galadril** [comment]
Do you suggest to implement search / filter in a different way?

**Comment by RoadXY** [comment]
I'll look into it tonight but somewhere a width setting should be different or a different line out of a widget.

**Comment by galadril** [comment]
Still an issue??
I use default controls and behaviour for Android.

On my nexus the Searchview overwrites the overflow menu button.. to see the menu button back, you have to close the searchview

This is implemented for lots of other apps the same way...

So close this issue?(normal behavious for Android apps)??

**Comment by RoadXY** [comment]
Looked through the code and I have to agree: it's all standard Android.
Closing issue.
