### ISSUE TITLE
Weather - more info

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#44]
I would like to see more info.

Like:
"HumidityStatus" -> "Wet"
"ForecastStr" -> "Rain"
"Barometer" -> "1008"
"DewPoint" -> "3.97"

**Comment by galadril** [comment]
Added in v0.1.139
Also in the InfoDialog:

![screenshot_20151125-102802](https://cloud.githubusercontent.com/assets/14561640/11393379/ac6097f4-935f-11e5-8b4b-6195d1769ce3.png)
![screenshot_20151125-101900](https://cloud.githubusercontent.com/assets/14561640/11393378/ac5da76a-935f-11e5-946e-9e02ffb4dae4.png)

**Comment by RoadXY** [comment]
Damn, even before I get the chance to think it through it's already done!
