### ISSUE TITLE
error at welcome wizzard.

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#50]
value- at signallever of type java.lang.String cannot be converted to int.
Please correct the data on the previeous page.

the above message I get in the wizzard on my nexus tablet.
I use a local Ip htttp 8080
username and pass.    and not a different server.

**Comment by RoadXY** [comment]
Did you try and closing the app and retry?
Doesn't seem logical to crash there.

**Comment by remb0** [comment]
yes I did :)

but I gonna flash my nexus tablet to marsmallow and try again.

Met vriendelijke groet,

Remco van Geel

2015-11-27 19:33 GMT+01:00 Robin van Kekem notifications@github.com:

**Comment by RoadXY** [comment]
Great!

I've tried on the emulator and my own tablet and did not have any issues.

**Comment by galadril** [comment]
still a problem?

**Comment by remb0** [comment]
nope gone :)
