### ISSUE TITLE
Thermostat can be controlled in whole steps

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#51]
Tthe thermostat set can be controlled in steps of 0.5   but in the app only with whole   numbers.

Maybe a wheel or something else (like you set your alarm timer) can be easier to control. every change now result in a refresh of the page and you must scroll down every time to hit the + , till you are on the number you wish.

**Comment by RoadXY** [comment]
Your first issue is already covered in issue #8 

For your second issue: we'll look into it.

**Comment by dadegeest** [comment]
https://github.com/galadril/DomoticzForAndroid/pull/60 
Hope it will not brake something else. With my Domoticz this works good

**Comment by galadril** [comment]
I wil build this merge in v0.1.144 Thanks

**Comment by RoadXY** [comment]
Great!

**Comment by remb0** [comment]
works!!

**Comment by remb0** [comment]
no controls on dashboard.
and when click on + or -   every step the app scrolls to top. (my device is one of the last so I have to scrol from top to bottom when i want to adjust from 16 to 21 in steps of 0.5.   10 scrols :)

**Comment by galadril** [comment]
no controls on dashboard. >
#8

**Comment by galadril** [comment]
"and when click on + or - every step the app scrolls to top. (my device is one of the last so I have to scrol from top to bottom when i want to adjust from 16 to 21 in steps of 0.5. 10 scrols :)"

Please check if you've still have this issue in the next version!

**Comment by remb0** [comment]
it work! with a small lagg. but faster then scrolling! :)

**Comment by galadril** [comment]
by bryan241 
Clicking the + for a thermostat will increase the temp with 1 degree.
Clicking on the - will decrease the temperature with 0.5 degrees, only the first time. After the first time the temperature gets decreased with 1 degree.
Pressing multiple times on the + does not work either.

http://www.domoticz.com/forum/viewtopic.php?f=37&t=8884&start=300#p67210

**Comment by RoadXY** [comment]
Wrong post
