### ISSUE TITLE
Scenes are crashing when protected is on

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#55]
when a scene is protected with password the scenes sections in the app is crashing.
I removed the protection and its fine now.

the scene is protected because it's my deadmanswitch. the whole house goes off :P

**Comment by galadril** [comment]
Fixed in v0.1.142

![screenshot_20151202-084318](https://cloud.githubusercontent.com/assets/14561640/11525137/d9853214-98d0-11e5-878a-6e9c2cfcd8aa.png)
