### ISSUE TITLE
scroll wheel/rgb color chooser example

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#56]
light controller (free)  is a wunderfull program to change the color of the milight rgb led bulbs!
can this be copied to domoticz on the smartwatch.    it's easy and nice.

**Comment by galadril** [comment]
Note; I've added a color picker on the switch screen :)

![2](https://cloud.githubusercontent.com/assets/14561640/11570661/ae80120e-99f8-11e5-9efe-8130391ca6a6.png)
![1](https://cloud.githubusercontent.com/assets/14561640/11570660/ae7ebfda-99f8-11e5-8b17-9b3bc9b72444.png)

**Comment by remb0** [comment]
Nice! better then noting.   but an Hexcode is not necessary i think.
and I think it is a little bit more difficult to pic the right color then a color wheel.

**Comment by RoadXY** [comment]
Realy nice @galadril

**Comment by galadril** [comment]
Omg.. your creating issues quicker that I can solve them..
Here the new version as a color wheel.

![colorpicker](https://cloud.githubusercontent.com/assets/14561640/11585795/d087ba2a-9a6e-11e5-8cb9-f25c3a1adb7b.png)

**Comment by remb0** [comment]
haha galadril you are great.   But I don't want to push you, and not suspecting that you do it the same day :P 
Or doing some ideas at all.

**Comment by jjnj023** [comment]
Is it also RGBW? It is not clear how to select white instead of a color.
