### ISSUE TITLE
On/Off button instead of on/off slider and show level slider always

### ISSUE THREAD

**Issue by dadegeest** [galadril/DomoticzForAndroid#59]
It's not a bug but more a request.
You can only see the dimmer sliders when a swtich is on in the app. Problem with KAKU is when you control the light with another remote, Domoticz will still say its off. You can't change the level of the light at that moment. When you press on the light will go oooonnnnn.....offffffff. :-)

On the otherside when the light is on (with another remote) you have to turn in on in the app first before you can switch the light off.

**Comment by galadril** [comment]
i think it's just the matter of refresh.. you have the app still open, while putting the light off via different system. Just swipe down in the app to refresh a list.

**Comment by RoadXY** [comment]
And I like the clean look of one slider instead of two buttons, imho.

**Comment by dadegeest** [comment]
I agree that it looks better how it is now. It's has nothing to do with refresh. Maybe we can make it both and let the user choose what they want with a setting.

**Comment by galadril** [comment]
I don't want to implement all kind of (user optinion) flavors with all kinds of settings...

**Comment by RoadXY** [comment]
Agreed. Options lead to confusion.
