### ISSUE TITLE
Permissions - Ask permissions only when needed

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#6]
Currently when starting the app for the first time on Android Marshmallow, Domoticz immediately requests all permissions as advised by the Android guidelines for permissions here:
http://developer.android.com/training/permissions/best-practices.html#dont-overwhelm

Relative parts:
_If you confront the user with a lot of requests for permissions at once, you may overwhelm the user and cause them to quit your app. Instead, you should ask for permissions as you need them._

_If your app provides a tutorial, it may make sense to request the app's essential permissions at the end of the tutorial sequence._

_Instead, wait until the user tries to use the feature which requires the permission and ask for the permission then._

**Comment by galadril** [comment]
I've fixed this matter in v0.1.142
