### ISSUE TITLE
Set Scene on Dashboard not working

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#62]
At this moment you can't save a Scene or Group as favorite.

**Comment by RoadXY** [comment]
Tested and confirmed

**Comment by RoadXY** [comment]
Also: when a scene (or group, the same issue) is favorite in Domoticz website it will not show up in the Domoticz app on the dashboard.

**Comment by galadril** [comment]
Fixed in next version
- Fixed the save favorite function for Scenes
- Added Scenes + Groups to Dashboard
