### ISSUE TITLE
Geofence - enhance dialog and UX

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#63]
I'm currently (still) working on this every night (so please don't change any file associated with it)!
Trying to find how to use onItemClick in listview (onItemLongClick works though).

Also in the add location dialog only a part of the address is shown.
Will continue to work on this tonight.

Screenshots:

Automatically find local address:
![screenshot_20151203-093114](https://cloud.githubusercontent.com/assets/3482284/11555504/00f4a08e-99a1-11e5-96ed-5ff13ccd88a2.png)

Edit radius and a (non-) working manual button for manual input of Latitude and Longitude input:
![screenshot_20151203-093203](https://cloud.githubusercontent.com/assets/3482284/11555516/122256d0-99a1-11e5-865b-2f01a8551245.png)

New Geofence overview:
![screenshot_20151203-093213](https://cloud.githubusercontent.com/assets/3482284/11555540/3b9254d4-99a1-11e5-8ef7-d8a177ae5b1c.png)

**Comment by galadril** [comment]
Looks good!

**Comment by arjen8** [comment]
Additional question (without creating a new issue): After adding a geofence location, the google maps image isn't visible. According to your images, it has to work properly. How is this possible?

![screenshot_2015-12-03-09-44-15](https://cloud.githubusercontent.com/assets/11772754/11555713/8a43e1f0-99a2-11e5-834c-18884ebcf48f.jpeg)

**Comment by RoadXY** [comment]
You build your own APK with your own debug key.
The release APK, which are signed by Galadril's developer key, are white listed on his Google Developer Console.
I had my debug key white listed on his Developer Console to test this ;-)

See the logcat on your phone.

**Comment by arjen8** [comment]
Ah thanks for explaining!

**Comment by galadril** [comment]
How are you progressing with this case?
I needed to change the GeoSettings activity because of location issues..

The LocationManager class of Google contained to many bugs, I needed to rewrite it to the New Google API (via GoogleApiClient connection).

**Comment by RoadXY** [comment]
Oh okay.
I'll finish my current work and create a pull request

**Comment by RoadXY** [comment]
Pull request: https://github.com/galadril/DomoticzForAndroid/pull/79

**Comment by galadril** [comment]
Nice one, we only need to implement 'Manual' to close this case :+1:

**Comment by RoadXY** [comment]
Yes, but you needed to implement several changes to the Geo activity so I did it with some rush ;-)

**Comment by RoadXY** [comment]
![screenshot_20151212-124403](https://cloud.githubusercontent.com/assets/3482284/11761727/39982b98-a0ce-11e5-8fc3-8ed6b5726bd7.png)
![screenshot_20151212-124329](https://cloud.githubusercontent.com/assets/3482284/11761728/41445092-a0ce-11e5-9a00-9528748b236e.png)

**Comment by RoadXY** [comment]
In commit:
https://github.com/RoadXY/DomoticzForAndroid/commit/2a2c3ef341575abb1b5f907103d45cae924ae33b
and
https://github.com/RoadXY/DomoticzForAndroid/commit/44765813cc822cb25fcebaeae50c4f22d2f9c98d

**Comment by RoadXY** [comment]
@galadril, could you test the manual (lat/long) implementation?
And the way I implemented switching layout for manual and address?

Thanks!
