### ISSUE TITLE
all devices by utilities

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#64]
before it were only the utilities from domoticz. now I see all devices (1.144)

**Comment by RoadXY** [comment]
Can you create a screenshot please?

**Comment by remb0** [comment]
I can but in fact that would be  a lot of screenshots.
Because of the fact that it displays everything I have in domoticz.   weather, devices, scenes etc.
and every item has  the buttons:   day month year under it.

**Comment by RoadXY** [comment]
Ok.
One screenshot as an example?

**Comment by remb0** [comment]
ok here you go!
![screenshot_2015-12-03-21-05-37](https://cloud.githubusercontent.com/assets/649642/11572465/bf5abb7a-9a01-11e5-93d8-39934250c804.png)

LOL on my pc I see colored blocks around the text: day month year.  I don't see that clear on my phone.  I think a brightjes thing of my phone :P

**Comment by galadril** [comment]
Found the issue.
Fixed in next version!
