### ISSUE TITLE
information in de readme about debugging

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#65]
maybe it's an good idea to post some rules and tips in the readme about debugging.
there is an debugging function in the app   but what does this do  and by sending crashreports who get's it etc.

I think a wiki isn't needed because the app is so easy and self explaining.

**Comment by galadril** [comment]
Added a page to the wiki (better that main readme)

https://github.com/galadril/DomoticzForAndroid/wiki/Debugging
