### ISSUE TITLE
Multilanguage with help of transiflex

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#66]
With transiflex it's simply to translate the words in the app in the languages users needed.
This way the app can be multilanguage and be downloaded much more.

**Comment by RoadXY** [comment]
I have 2 services ready for translation with a sample in it.

Which one do we wan to use?

https://github.com/galadril/DomoticzForAndroid/wiki/Translations

**Comment by galadril** [comment]
I would vote for Crowdin.. you??

**Comment by RoadXY** [comment]
Me too Crowdin

**Comment by galadril** [comment]
So Crowdin then?

**Comment by RoadXY** [comment]
Yes. We are the lead developers, lets make the decision  :-D

Crowdin it is!
