### ISSUE TITLE
Icons a function through using colors.

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#67]
now devices that are on and off are the same colours.
is it possible to change this?  red when off  other colour when on?

or always a transparant overlay above the picture and when on: the transparancy of the overlay set to 100.

**Comment by galadril** [comment]
- I changed the alpha of the icon to 50% when the switch if turned off

![screenshot_20151206-163849](https://cloud.githubusercontent.com/assets/14561640/11614111/4a3d8172-9c38-11e5-8209-70fd017466ca.png)
