### ISSUE TITLE
camera bigger version gives a blank screen.

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#68]
the camera displays the miniature fine.   but when I open the thumbnail for a bigger version.  but that one is empty.  a blank screen.
when i enable debug and then open the camera it's still blank.

**Comment by remb0** [comment]
and my domoticz loggings displays this message:
2015-12-03 20:51:42.105 Error: Error executing uvccapture command. returned: 256
2015-12-03 20:51:43.424 Error: Error executing uvccapture command. returned: 256

**Comment by RoadXY** [comment]
Any screenshots?

**Comment by galadril** [comment]
Found a bug, fixed in next version!
