### ISSUE TITLE
Switches page gives error

### ISSUE THREAD

**Issue by dadegeest** [galadril/DomoticzForAndroid#69]
OOPS! 
Something went wrong
No value for result
when I go to the Switches page.

Already removed all my devices except the light but that's also not working.

**Comment by RoadXY** [comment]
Did you try again? (Probably stupid question)

**Comment by dadegeest** [comment]
Yes I did :-)
Even removed all my devices and tried again with only 1 light switch. rebuild the app. Same problem. I try to catch the problem in the debugger.

**Comment by dadegeest** [comment]
Seem like there is a bug in Domoticz with Kodi. I had Kodi in my hardware list but disabled. Domoticz tries to send the kodi information through the webservice.

**Comment by RoadXY** [comment]
Do you still have the logcats for future reference?
