### ISSUE TITLE
Error handling - JSON exception, catch and give user friendly error

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#7]
If the exception is a JSON exception it is most likely the user doesn't have the specific topic (plans in my example).
Would be a good idea to act on JSON exceptions and show a user friendly message like 'No plans' or something like that.

Example JSON which will throw an exception because there is no result:

```
response = {org.json.JSONObject@4682} "{"status":"OK","title":"Plans"}"
 nameValuePairs = {java.util.LinkedHashMap@4684}  size = 2
  0 = {java.util.LinkedHashMap$LinkedEntry@4688} "status" -> "OK"
  1 = {java.util.LinkedHashMap$LinkedEntry@4689} "title" -> "Plans"
```

**Comment by RoadXY** [comment]
Solved in:
https://github.com/galadril/DomoticzForAndroid/pull/115

But I need an user friendly image, I guess?
![device-2015-12-20-200843](https://cloud.githubusercontent.com/assets/3482284/11919559/0ae6fcb4-a756-11e5-8740-8553c7d74e88.png)
![device-2015-12-20-200759](https://cloud.githubusercontent.com/assets/3482284/11919560/11eca91e-a756-11e5-8b4b-6c93b7fa1fc1.png)

**Comment by RoadXY** [comment]
@galadril could you mock up an image? Do you have any inspiration for this? :-)

**Comment by galadril** [comment]
i'll see what i can do.
I do like how  it looks now!

**Comment by RoadXY** [comment]
I've implemented it on the parent fragment: domoticzFragment and DomoticzCardFragment so it should work for all fragments!

My first idea for the picture would be something with empty in it and maybe an house or something?
Creativity is not my strongest part :-S

**Comment by galadril** [comment]
Or we use one of the existing circle-icons pack.. ?

![dev](https://cloud.githubusercontent.com/assets/14561640/11926515/d67ee3a4-a7c5-11e5-9efd-2f340c8f30d2.png)
![gear](https://cloud.githubusercontent.com/assets/14561640/11926516/d6815ca6-a7c5-11e5-9406-86cf9d3ef1be.png)
![paintroller](https://cloud.githubusercontent.com/assets/14561640/11926518/d686d406-a7c5-11e5-9e1b-988efb88fba5.png)
![travelerbag](https://cloud.githubusercontent.com/assets/14561640/11926517/d68477f6-a7c5-11e5-873d-4c074bc9f6b0.png)
![x](https://cloud.githubusercontent.com/assets/14561640/11926519/d689ef24-a7c5-11e5-9512-5e643d4328c5.png)

All icons":
http://flaticons.org/free-circle-icon-set/

**Comment by RoadXY** [comment]
I'll take a took!
I think it should be black/white but that should be to hard.

**Comment by galadril** [comment]
Maybe something minimalistic like:
![1](https://cloud.githubusercontent.com/assets/14561640/11928702/ee87868a-a7d5-11e5-8966-9991b4efeac1.png)

??

**Comment by RoadXY** [comment]
I think we should use something larger.

What I've came up with:

![device-2015-12-21-131428](https://cloud.githubusercontent.com/assets/3482284/11930606/4c925d9a-a7e5-11e5-9c7c-165986360df5.png)

Or b/w

![device-2015-12-21-131912](https://cloud.githubusercontent.com/assets/3482284/11930627/720c8424-a7e5-11e5-8349-80856d1f45b4.png)

**Comment by galadril** [comment]
Looks good.. i do like some color :+1:

**Comment by RoadXY** [comment]
Yeah, thought b/w would be better but it's not.
Only: the quality of the master/base image is too low :-S

**Comment by galadril** [comment]
![g5498](https://cloud.githubusercontent.com/assets/14561640/11930876/c54ab9e2-a7e7-11e5-897f-c626b0be659a.png)

**Comment by RoadXY** [comment]
Great!
