### ISSUE TITLE
Push Notifications from Domoticz

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#72]
Implement Push Notifications from Domoticz system to the Android app!
https://developers.google.com/cloud-messaging

This also requires someone to implement Android push notifictions on the Domoticz side...

![pushnotifications](https://cloud.githubusercontent.com/assets/14561640/11613278/5561afb4-9c1b-11e5-9af1-01c0afb9f98c.png)

**Comment by RoadXY** [comment]
Jeej, an milestone!
But, great idea!
Hopefully someone of the server devs is willing to participate on this.

**Comment by galadril** [comment]
Nice tutorial/description:
https://github.com/codepath/android_guides/wiki/Google-Cloud-Messaging

So the app needs to register on the Google Connection servers, then we need to save that token in Domoticz.
- Can we ask the Domoticz developers to implement a json post call to save a token (string)
- Maybe we should be able to store multiple tokens (if users has 3 phones in a house for example)
- And then Domoticz can send notifications with that registration token:

curl -s "https://android.googleapis.com/gcm/send" -H "Authorization: key=[API_KEY_HERE]" -H "Content-Type: application/json" -d '{"to": "[REG_TOKEN_HERE]", "data": {"messages": "text"}}'

Looks not to hard..

**Comment by RoadXY** [comment]
Have been worrying about all the api keys being readable (since both Domoticz server and Domoticz Android client are open source) and found this:

http://stackoverflow.com/questions/32827977/can-i-share-google-cloud-messaging-api-key

**Comment by galadril** [comment]
Or use environment variables in Android Studio for secret things
http://en.wikipedia.org/wiki/Environment_variable

If they get the branch, they get a question to setup the environment variable 
(so they need to create a key for their own..)

I think we should still do that for the Geofence api key :)

**Comment by RoadXY** [comment]
http://www.rainbowbreeze.it/environmental-variables-api-key-and-secret-buildconfig-and-android-studio/

Nice find!
Going to use this for my other projects to!

**Comment by acmkonings** [comment]
As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to [Firebase Cloud Messaging (FCM)](http://firebase.google.com/docs/cloud-messaging/), which inherits the [..] GCM infrastructure. Migration documentation is available.

**Comment by galadril** [comment]
This is an old repo.. we're using FCM already
