### ISSUE TITLE
gas/water and electricity

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#75]
comsumption in the app is not very clear

app:
data: 361136;357047;0;0;230;0
domoticz: 
    230 Watt
    7231.694
    today: 1.518
wish:
other icon
current usage, today, (overall)

water
app:    11.562 m3
domoticz:
0.24m3
11.562 m3

wish: 
other icon
today, (overall)

gas
app:
data: 1348.076

domoticz:
0.084 m3

wish:
other icon
today, (overall)

**Comment by galadril** [comment]
Please add printscreens.. that always helps!

I need per item:
- a screenshot of the app how the line looks
- a screenshot of the line in Domoticz
- how does the device json looks like via the next json call:  
  **http://ip:port/json.htm?type=devices&used=true&order=Name**  
  (i don't need the whole json result, just the devices your talking about)

**Comment by remb0** [comment]
you are right.
![screenshot_2015-12-09-18-44-54](https://cloud.githubusercontent.com/assets/649642/11693468/5d7c7e4a-9ea5-11e5-910a-7905f868b74d.png)
![screenshot_2015-12-09-18-45-29](https://cloud.githubusercontent.com/assets/649642/11693467/5d7bfc18-9ea5-11e5-8079-f11c0ad451ef.png)
![domoticz](https://cloud.githubusercontent.com/assets/649642/11693469/5d7d5b6c-9ea5-11e5-9f42-9db0c94da436.png)

```
 {
     "AddjMulti" : 1.0,
     "AddjMulti2" : 1.0,
     "AddjValue" : 0.0,
     "AddjValue2" : 0.0,
     "BatteryLevel" : 255,
     "Counter" : "7265.272",
     "CounterDeliv" : "0.000",
     "CounterDelivToday" : "0.000 kWh",
     "CounterToday" : "5.101 kWh",
     "CustomImage" : 0,
     "Data" : "3680263;3585009;0;0;630;0",
     "Description" : "",
     "Favorite" : 1,
     "HardwareID" : 1,
     "HardwareName" : "Smart meter",
     "HardwareType" : "P1 Smart Meter USB",
     "HardwareTypeVal" : 4,
     "HaveTimeout" : false,
     "ID" : "1",
     "LastUpdate" : "2015-12-09 18:46:06",
     "Name" : "Energy",
     "Notifications" : "false",
     "PlanID" : "17",
     "PlanIDs" : [ 17, 19 ],
     "Protected" : false,
     "ShowNotifications" : true,
     "SignalLevel" : "-",
     "SubType" : "Energy",
     "SwitchTypeVal" : 0,
     "Timers" : "false",
     "Type" : "P1 Smart Meter",
     "TypeImg" : "counter",
     "Unit" : 1,
     "Usage" : "630 Watt",
     "UsageDeliv" : "0 Watt",
     "Used" : 1,
     "XOffset" : "687",
     "YOffset" : "462",
     "idx" : "2"
  },
```

{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "1362.731",
         "CounterToday" : "0.734 m3",
         "CustomImage" : 0,
         "Data" : "1362.731",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 1,
         "HardwareName" : "Smart meter",
         "HardwareType" : "P1 Smart Meter USB",
         "HardwareTypeVal" : 4,
         "HaveTimeout" : false,
         "ID" : "1",
         "LastUpdate" : "2015-12-09 18:44:56",
         "Name" : "gas",
         "Notifications" : "false",
         "PlanID" : "17",
         "PlanIDs" : [ 17 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Gas",
         "SwitchTypeVal" : 1,
         "Timers" : "false",
         "Type" : "P1 Smart Meter",
         "TypeImg" : "counter",
         "Unit" : 2,
         "Used" : 1,
         "XOffset" : "684",
         "YOffset" : "372",
         "idx" : "3"
      },

```
 {
     "AddjMulti" : 1.0,
     "AddjMulti2" : 1.0,
     "AddjValue" : 0.0,
     "AddjValue2" : 0.0,
     "BatteryLevel" : 255,
     "Counter" : "12.519 m3",
     "CounterToday" : "0.078 m3",
     "CustomImage" : 0,
     "Data" : "12.519 m3",
     "Description" : "",
     "Favorite" : 1,
     "HardwareID" : 13,
     "HardwareName" : "Virtual",
     "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
     "HardwareTypeVal" : 15,
     "HaveTimeout" : false,
     "ID" : "82605",
     "LastUpdate" : "2015-12-09 18:46:04",
     "Name" : "Wat",
     "Notifications" : "false",
     "PlanID" : "0",
     "PlanIDs" : [ 0 ],
     "Protected" : false,
     "ShowNotifications" : true,
     "SignalLevel" : "-",
     "SubType" : "Counter Incremental",
     "SwitchTypeVal" : 2,
     "Timers" : "false",
     "Type" : "General",
     "TypeImg" : "counter",
     "Unit" : 1,
     "Used" : 1,
     "XOffset" : "0",
     "YOffset" : "0",
     "idx" : "606"
  },
```

**Comment by galadril** [comment]
Thanks!

**Comment by galadril** [comment]
Please check if it looks better in the next version.

**Comment by remb0** [comment]
I will..  thanks!

**Comment by galadril** [comment]
And does it looks better now??

**Comment by remb0** [comment]
very good.
only gas and water does not display the totals of today.
and has stil the same icon (not a real problem though.)

**Comment by galadril** [comment]
Can you make a guest user, so I could check with your domoticz system?

**Comment by galadril** [comment]
Think we can close this (did some changes in v0.1.155)
