### ISSUE TITLE
Dashboard - A thermostat on the dashboard doesn't have controls

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#8]
While the controls are there when in 'Utilities'

![dashboard - thermostat controls](https://cloud.githubusercontent.com/assets/3482284/11257477/030c9c78-8e52-11e5-8ccd-d6963e9a71c9.png)

**Comment by galadril** [comment]
Fixed in v 0.1.157

**Comment by RoadXY** [comment]
I think the showed data isn't correct yet.
The last seen data shouldn't be there while the switch in settings is off.

![screenshot_20151222-000745](https://cloud.githubusercontent.com/assets/3482284/11943685/1d696936-a840-11e5-9000-33177de627c9.png)

**Comment by galadril** [comment]
Better this way:: ?

![screenshot_20151222-151353](https://cloud.githubusercontent.com/assets/14561640/11956988/b96fcb9e-a8be-11e5-9bed-78f650806cde.png)

**Comment by RoadXY** [comment]
Jeeej!
