### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by dadegeest** [galadril/DomoticzForAndroid#83]
It's only possible to use the app vertical and not horizontal. I would like to use it on a tablet that is hanging horizontal on the wall. Is there a reason why it's build to only use in portrait mode?

**Comment by RoadXY** [comment]
Because orientation changes are difficult to handle with Android and a-sync tasks (like the volley util were using).
And because it was holding me back, back when I started, to get something useful :-D

**Comment by galadril** [comment]
![3](https://cloud.githubusercontent.com/assets/14561640/11777858/2a72d26a-a251-11e5-96e5-e92ec19bf522.png)
![1](https://cloud.githubusercontent.com/assets/14561640/11777857/2a6f1fee-a251-11e5-9598-151953f2ea9d.png)
![2](https://cloud.githubusercontent.com/assets/14561640/11777859/2a936a34-a251-11e5-82db-81377199e59a.png)

**Comment by remb0** [comment]
not in 1.151 I suppose ?
only the setting page is in landscape..

**Comment by galadril** [comment]
next version

**Comment by RoadXY** [comment]
No crashes when rotating while fetching devices?
That's what I had when I began on this.

**Comment by galadril** [comment]
I had to change some settings in the Manifest to make it work..
