### ISSUE TITLE
Intent leaked after welcome wizard

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#86]
See gist here:
https://gist.github.com/RoadXY/c48b8ea1dccad3f943d1

**Comment by galadril** [comment]
Looks like same problem like #88

**Comment by RoadXY** [comment]
In my humble opinion? No :-)

In the PhoneConnectionUtil there is a method called stopReceiver which unregisters the broadcastreceiver (for receiving wifi ssid's) (line 57 in PhoneConnectionUtil)
On every stop of the mainactivity (line 138) it tries to unregister this broadcast receiver but it wasn't started/initialized.

This issues intent is leaked when WelcomePage3 is paused/stopped.

**Comment by galadril** [comment]
Think i've fixed these issues with the next version (please check)
