### ISSUE TITLE
Welcome wizard - Detect if only local wifi settings are empty

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#89]
Maybe we could help the user on page 4 if only the page with 'Use different address for local connection' is left blank.
If the fields are left blank explain?

**Comment by galadril** [comment]
?

**Comment by RoadXY** [comment]
If you leave the switch on for a different address for the Domoticz Server settings and proceed to the next screen, the message is that not all fields have data.
Maybe a little intelligent test that only the fields for a local/different server address isn't complete?

**Comment by galadril** [comment]
I fixed this by defailting the switch to 'false'...
So a user needs to flip the switch to true if he needs a different address for local.

**Comment by RoadXY** [comment]
Sometimes I think difficult. Great solution
