### ISSUE TITLE
Weather - Some units are missing

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#9]
Units for rain and wind are missing

![weather - units are mising](https://cloud.githubusercontent.com/assets/3482284/11257619/12eba1ce-8e53-11e5-84a0-e45bc4344e81.png)

**Comment by galadril** [comment]
It's also not in the json result of Domoticz.. so should this not be a Domoticz case?
http://%Server%:%Port%/json.htm?type=devices&filter=weather&used=true&order=Name

"Name" : "Hank - Regen",
"Data" : "0;0.0",

**Comment by RoadXY** [comment]
I'll ask Remco to contact the Domoticz developer for the query.

**Comment by RoadXY** [comment]
Created a bug report on the Domoticz forum on advice of Remco:
http://domoticz.com/forum/viewtopic.php?f=6&t=9005

**Comment by galadril** [comment]
Think i could close this issue.

**Comment by RoadXY** [comment]
You could, lol. Only I beat you to it. :-D

**Comment by galadril** [comment]
:)
