### ISSUE TITLE
Temperature page - Wind

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#90]
Wind was not detected correctly and the text still displayed with 'temperature'.

**Comment by RoadXY** [comment]
Solved in: https://github.com/RoadXY/DomoticzForAndroid/commit/3fe411fc0bea867884d1cc04ac64364766c3fbd9

**Comment by galadril** [comment]
:+1:

**Comment by galadril** [comment]
Confimed that it's working now

**Comment by RoadXY** [comment]
But is this the nicest solution?
Currently it displays the wind direction in degrees and Cardinal direction (https://en.wikipedia.org/wiki/Cardinal_direction)

However there is more info available:
Chill (perceived decrease in air temperature felt by the body on exposed skin due to the flow of air),
Gust (Short bursts of high speed wind), 
Speed, 
Temp

Current:
![device-2015-12-14-101037](https://cloud.githubusercontent.com/assets/3482284/11776915/00d27092-a24b-11e5-9e2c-cb873c1c0517.png)
