### ISSUE TITLE
Running app on Android Kitkat

### ISSUE THREAD

**Issue by arjen8** [galadril/DomoticzForAndroid#99]
Hi,

After compiling the app in Android Studio, I get the following errors after running the app on a Android Kitkat 4.4 (API 19) mobile phone (Huawei P7):
- 12-15 12:35:32.580 366-366/? E/dalvikvm: could not disable core file generation for pid 366: Operation not permitted
- 12-15 12:35:33.250 366-415/nl.hnogames.domoticz E/GMPM: getGoogleAppId failed with status: 10
- 12-15 12:35:33.260 366-415/nl.hnogames.domoticz E/GMPM: Uploading is not possible. App measurement disabled
- 12-15 12:35:33.600 366-366/nl.hnogames.domoticz E/dalvikvm: Could not find class 'nl.hnogames.domoticz.Utils.SharedPrefUtil$1', referenced from method nl.hnogames.domoticz.Utils.SharedPrefUtil.setGeoFenceService
- 12-15 12:35:33.800 366-366/nl.hnogames.domoticz E/dalvikvm: Could not find class 'nl.hnogames.domoticz.Welcome.WelcomePage2$1', referenced from method nl.hnogames.domoticz.Welcome.WelcomePage2.onCreateView
- 12-15 12:35:33.810 366-366/nl.hnogames.domoticz E/dalvikvm: Could not find class 'nl.hnogames.domoticz.UI.MultiSelectionSpinner', referenced from method nl.hnogames.domoticz.Welcome.WelcomePage3.getLayoutReferences
- 12-15 12:35:33.820 366-366/nl.hnogames.domoticz E/dalvikvm: Could not find class 'nl.hnogames.domoticz.Welcome.WelcomePage3$3', referenced from method nl.hnogames.domoticz.Welcome.WelcomePage3.setProtocol_spinner
- 12-15 12:35:33.820 366-366/nl.hnogames.domoticz E/dalvikvm: Could not find class 'nl.hnogames.domoticz.Utils.PhoneConnectionUtil', referenced from method nl.hnogames.domoticz.Welcome.WelcomePage3.setSsid_spinner
- 12-15 12:35:33.820 366-366/nl.hnogames.domoticz E/dalvikvm: Could not find class 'nl.hnogames.domoticz.Welcome.WelcomePage3$5', referenced from method nl.hnogames.domoticz.Welcome.WelcomePage3.setStartScreen_spinner
- 12-15 12:35:33.830 366-366/nl.hnogames.domoticz E/dalvikvm: Could not find class 'nl.hnogames.domoticz.Welcome.WelcomePage4$1', referenced from method nl.hnogames.domoticz.Welcome.WelcomePage4.checkConnectionData

Running the app on a Nexus phone, all work fine!

What could cause these errors?

**Comment by arjen8** [comment]
After some investigation, I solved this by adding the following code:

App -> AppController.java

```
public class AppController extends Application {

......

@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

.... 

}
```

Build.gradle (app)

```
dependencies {
    .....
    compile 'com.android.support:multidex:1.0.1'
....
}
```

**Comment by galadril** [comment]
:+1: Thanks

**Comment by galadril** [comment]
I'll add your suggested fixes in the next version

**Comment by galadril** [comment]
can this be closed?

**Comment by arjen8** [comment]
Sorry for my late reply. I'll check it shortly.

**Comment by arjen8** [comment]
I can confirm that it's fixed! Thnx
